### ISSUE TITLE
Breadcrumb on product page missing

### ISSUE THREAD

**Issue by KidKime** [rb2/opencart-seopro#1] opened 2014-05-23 12:14 UTC
Hi, when I navigate to teh product page, there is no breadcrumb, only:

Home > Product name

whereas it should be

Home > category > category > product name

**Comment by rb2** [comment] 2014-05-23 16:51
I don't use SeoPro: forked it just to add description.

Seems the repo doesn't have full SeoPro module, just several main files to be fixed by the crowd. So if you installed it from here - you simply don't have SeoPro module installed and it doesn't work.

The module is free, but originally was part of the "russian Opencart pack" (ocStore) since 2011 or 2012, and didn't exist and maintained as separate module.

I will look into it. Maybe will find the full set of files. But I really don't want to use vQmod and maintain the whole module.

**Comment by rb2** [comment] 2014-06-24 09:20
@KidKime , I have added full SeoPro to the repo. Tested it on Opencart v1564.

Unable to reproduce the bug you described.

What I do to check:
- enable SeoPro in store settings (tab "Server")
- enable using category path in URl
- check that product and category have not empty "SEO keyword" field
- link the product to one or many categories
- select one category as product's MAIN CATEGORY from appropriate dropdown select box
- look into `system/cache` directory and empty it (leave only `index.html`)
- go to the store frontend and open tested category and product page

I see right URL and right breadcrumbs on the product page.
If product assigned to several categories, navigate through alternative categories and click the product: as result you will be redirected to the main category of the product.

Product page contains full path. In my case (for products I tested):
- Home » Tablets » Samsung Galaxy Tab 10.1
- Home » Components » Monitors » Apple Cinema 30"
  
  Home » Components » Monitors » Samsung SyncMaster 941BW

**Closed as completed** 2014-06-24 09:29 UTC
Labels: unable to reproduce
